### ISSUE TITLE
Upper case words and initial upper case words get wrong suggestions

### ISSUE THREAD

**Issue by snomos** [divvun/hfst-ospell-js#3]
For comparison, see this correct behavior:

```
$ echo "5 VATTIS" | hfst-ospell-office tools/spellcheckers/fstbased/desktop/hfst/se.zhfst 
@@ hfst-ospell-office is alive
&   VÁTTIS GÁTTIS BÁTTIS LÁTTIS RÁTTIS
$ echo "5 Vattis" | hfst-ospell-office tools/spellcheckers/fstbased/desktop/hfst/se.zhfst 
@@ hfst-ospell-office is alive
&   Váttis Gáttis Báttis Láttis Ráttis
$ echo "5 vattis" | hfst-ospell-office tools/spellcheckers/fstbased/desktop/hfst/se.zhfst 
@@ hfst-ospell-office is alive
&   váttis gáttis váttes báttis ráttis
```

ck-ospell + hfst-ospell-js give less optimal suggestions:

<img width="201" alt="vattis-1" src="https://cloud.githubusercontent.com/assets/1255285/19306953/63c69b08-9078-11e6-8cb0-d15e24ff534a.png">
<img width="193" alt="vattis-2" src="https://cloud.githubusercontent.com/assets/1255285/19306954/63e7e33a-9078-11e6-84e2-68158ccc06f9.png">
<img width="200" alt="vattis-3" src="https://cloud.githubusercontent.com/assets/1255285/19306955/63e94716-9078-11e6-8f4d-30a8118f5bca.png">

See the case handling code for hfst-ospell-office for how to get proper behaviour.

**Comment by snomos** [comment]
Commit eb617c7bcb8e24fcd78e016b0ccbf7ce725c80d6 fixes the initial upper case version, whereas all upper still gives bonanza suggestions:

<img width="221" alt="vattis" src="https://cloud.githubusercontent.com/assets/1255285/19360498/328c9a58-917f-11e6-9b5d-3bc4c0736100.png">

<img width="227" alt="vattis1" src="https://cloud.githubusercontent.com/assets/1255285/19360574/60dc67a8-917f-11e6-9def-f699c4e99959.png">

**Comment by bbqsrc** [comment]
Can you confirm this is fixed?

**Comment by snomos** [comment]
This is not fixed, the situation is the same as described in my previous comment.
